auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: vincentlws.github.io
url: http://vincentlws.github.io
feed: /atom.xml
author_info: <a href="http://vincentlws.github.io/">vincentlws</a>
